Count for subdirectories counts other users private ones
gridsuite/directory-server pull request #108
Opened 2023-12-04 13:38 UTC by lilian-houdelet

2023-12-06 14:12 UTC, Meklo approved these changes

2023-12-08 10:21 UTC, YenguiSeddik approved these changes

2023-12-08 10:39 UTC, YenguiSeddik requested changes
When creating a public directory "Test" and create a filter inside it by "userA" (it can be used by everyone), and then swithch to another user "userB" and open directory selector in gridsuite (from generator scaling for example), the directory "Test" appear but without an arrow and when clicking on it, it open and show the filter (it should have an arrow if it have a element that can be used)

2024-01-23 11:20 UTC, YenguiSeddik approved these changes

2024-01-23 13:35 UTC, merged