delete folder recursivly + add new endpoint : get element by uuid
gridsuite/directory-server pull request #11
Opened 2021-07-12 09:19 UTC by ChamseddineBhd

Signed-off-by: chamseddine <chamseddine.benhamed@ensi-uma.tn>

2021-07-12 15:42 UTC, niconoir commented on src/main/java/org/gridsuite/directory/server/DirectoryController.java
> +    public ResponseEntity<Mono<DirectoryAttributes>> getElementInfos(@PathVariable("directoryUuid") String directoryUuid) {
Why not name the function "getDirectoryInfos" (same name as the method called in service) ?

2021-07-12 15:42 UTC, niconoir commented on src/main/java/org/gridsuite/directory/server/DirectoryService.java
> +        return new DirectoryAttributes(entity.getParentId(), entity.getName(), new AccessRightsAttributes(entity.isPrivate()), entity.getOwner());
Maybe check if entity type is of DIRECTORY type before ?

2021-07-12 15:42 UTC, niconoir commented on src/main/java/org/gridsuite/directory/server/DirectoryService.java
> +        return Flux.fromStream(directoryElementRepository.findByParentId(null).stream().map(DirectoryService::toElementAttributes));
Why not return a Flux<DirectoryAttributes> instead of Flux<ElementAttributes> since the returned values are directories ?

2021-07-12 15:42 UTC, niconoir commented on src/main/java/org/gridsuite/directory/server/DirectoryService.java
> +    private void deleteElementTree(String elementUuid) {
Maybe provide a parameter to enable/disable recursive deletion ? User might want to be notified when he is trying to remove a directory containing sub-directories.

2021-07-13 08:11 UTC, FranckLecuyer requested changes
Maybe merge the 'DirectoryAttributes' and 'ElementAttributes' class into a signle one ?

2021-07-15 09:28 UTC, niconoir requested changes
It could be useful to add a unit test ensuring that when a directory is deleted, all its subdirectories are deleted too (ensure recursivity). Here, the directory deletion test only deletes a directory which has no children.

2021-07-15 10:03 UTC, FranckLecuyer approved these changes

2021-07-15 12:48 UTC, niconoir approved these changes

2021-07-15 14:15 UTC, merged