display trashed elements per owner
gridsuite/directory-server pull request #125
Opened 2024-04-02 13:50 UTC by ghazwarhili

2024-04-03 12:07 UTC, Mathieu-Deharbe commented
I am trying to test but don't get what I expect. I have 2 users, each one deleted a file. When i connect as one and click on restore I can see this : 

![corbeille](https://github.com/gridsuite/directory-server/assets/148252167/b9b34c25-8600-46ba-8815-3c08ff020f25)

The 2 files can be seen and selected.

But if I try to restore them only the one belonging to the user will be restored. The other will remain stashed and I won't have any error message or information whatsoever.

This does not match the US description.

2024-04-03 15:57 UTC, Mathieu-Deharbe commented
Ok first problem is fixed but I found something else : 

I have a situation in a folder. 
I duplicate it. 
I delete both.
Then I restore one => **both are restored instead of only the one I picked.**

I tried with 2 different users and folders and had twice the same bug.

2024-04-03 15:58 UTC, Mathieu-Deharbe requested changes
cf comment I just added in the PR about a possible bug.

2024-04-04 07:17 UTC, ghazwarhili commented
Based on the changed code and the description of the US, the reported bug of duplicated elemets does not align  or match with the requested from this PR. 

change request is to modify the code, not to report a bug that can be reproduced on main, however  we can report it to the PO.

2024-04-04 08:46 UTC, Mathieu-Deharbe requested changes
If I delete a private element (a situation from a private folder) I can't see it in the bin when I try to restore it. (the public elements can be seen and restored).

If I switch back to the main branch the element can be restored normally.

2024-04-04 08:46 UTC, Mathieu-Deharbe commented on src/main/java/org/gridsuite/directory/server/repository/DirectoryElementRepository.java
> +            "(e.isPrivate = false or (e.isPrivate IS NULL AND NOT EXISTS (SELECT 1 FROM DirectoryElementEntity parent WHERE parent.id = e.parentId AND parent.isPrivate = true)))" +
It seems to me that this second line requires the object to be public (private are all excluded). It might explain the problem I encountered.

2024-04-04 09:25 UTC, ghazwarhili commented on src/test/java/org/gridsuite/directory/server/DirectoryTest.java
> +        checkStashedElements(List.of(Pair.of(subDirAttributes1, 1L)));
the owner of subDirAttributes4 is different from that of subDirAttributes1

2024-04-04 09:32 UTC, ghazwarhili commented on src/main/java/org/gridsuite/directory/server/repository/DirectoryElementRepository.java
> -            "AND (e.owner = :userId OR e.isPrivate = false OR (e.isPrivate IS NULL AND NOT EXISTS (SELECT 1 FROM DirectoryElementEntity parent WHERE parent.id = e.parentId AND parent.isPrivate = true
Deleted because the value of isPrivate doesn't matter

2024-04-04 14:49 UTC, Mathieu-Deharbe approved these changes

2024-04-08 13:12 UTC, sBouzols commented on src/main/java/org/gridsuite/directory/server/repository/DirectoryElementRepository.java
>      List<DirectoryElementEntity> findAllStashedElements(@Param("uuids") List<UUID> uuids,
Then it's now writable by a JPA Query method :
`findByIdInAndStashedTrueAndOwner`

2024-10-14 13:16 UTC, closed without merging