Remove code used for stashing - add supervision classes to handle existing stashed elements deletion
gridsuite/directory-server pull request #129
Opened 2024-04-12 15:10 UTC by klesaulnier

2024-04-18 10:04 UTC, TheMaskedTurtle requested changes

2024-04-19 12:00 UTC, TheMaskedTurtle requested changes

2024-04-19 12:23 UTC, klesaulnier commented on src/main/java/org/gridsuite/directory/server/services/DirectoryRepositoryService.java
>          return directoryElementRepository.findAllByIdIn(elementUuids);
fixed

2024-04-19 12:23 UTC, klesaulnier commented on src/test/java/org/gridsuite/directory/server/utils/DirectoryTestUtils.java
> +package org.gridsuite.directory.server.utils;
fixed

2024-04-19 12:23 UTC, klesaulnier commented on src/test/java/org/gridsuite/directory/server/DirectoryElementRepositoryTest.java
> +package org.gridsuite.directory.server;
fixed

2024-04-19 12:23 UTC, klesaulnier commented on src/main/java/org/gridsuite/directory/server/DirectoryService.java
> +        studyToDeleteUuids.forEach(studyUuid -> notificationService.emitDeletedStudy(studyUuid, userId));
fixed

2024-04-22 10:34 UTC, merged