add getCasesCount
gridsuite/directory-server pull request #145
Opened 2024-06-11 08:50 UTC by AbdelHedhili

2024-06-18 11:51 UTC, achour94 requested changes

2024-06-18 11:51 UTC, achour94 commented on src/main/java/org/gridsuite/directory/server/repository/DirectoryElementRepository.java
> +    @Query("SELECT count(*) FROM DirectoryElementEntity WHERE owner=:owner AND type='CASE' OR type='STUDY'")
You forgot the parentheses in the query. 
`@Query("SELECT count(*) FROM DirectoryElementEntity WHERE owner=:owner AND (type='CASE' OR type='STUDY')")`

2024-06-18 11:51 UTC, achour94 commented on src/test/java/org/gridsuite/directory/server/DirectoryElementRepositoryTest.java
> +                createElement(UUID.randomUUID(), "case6", "CASE", "user2")
create another element with type 'STUDY' for user2 since this test does not detect the parentheses error :)

2024-06-18 12:41 UTC, achour94 approved these changes

2024-06-19 09:21 UTC, FranckLecuyer approved these changes

2024-06-21 08:50 UTC, merged