Remove all references to a specific element type.
gridsuite/directory-server pull request #150
Opened 2024-07-04 09:39 UTC by AAJELLAL

2024-07-09 16:04 UTC, sBouzols commented on src/main/java/org/gridsuite/directory/server/NotificationService.java
>      public static final String HEADER_STUDY_UUID = "studyUuid";
remove HEADER_STUDY_UUID as well

2024-07-09 16:06 UTC, sBouzols commented on src/main/java/org/gridsuite/directory/server/DirectoryService.java
> -    private final StudyService studyService;
Then remove StudyService.java file as well ?

2024-07-09 16:08 UTC, sBouzols requested changes
There are still occurences of STUDY, CONTINGENCY_LIST, FILTER, MODIFICATION, CASE etc...

2024-07-11 09:39 UTC, AAJELLAL commented
> There are still occurences of STUDY, CONTINGENCY_LIST, FILTER, MODIFICATION, CASE etc... Why do we have a `consumeStudyUpdate` here...



> There are still occurences of STUDY, CONTINGENCY_LIST, FILTER, MODIFICATION, CASE etc... Why do we have a `consumeStudyUpdate` here...

I have cleaned everything except the two test methods (testCountUserCases and testCountCasesByUser), which will be done later in a separate user story.

2024-07-11 09:40 UTC, AAJELLAL commented on src/main/java/org/gridsuite/directory/server/DirectoryService.java
> -    private final StudyService studyService;
Done.

2024-07-19 14:10 UTC, merged