chore: switch to common automated workflows from powsybl
gridsuite/directory-server pull request #168
Opened 2024-10-23 14:28 UTC by TheMaskedTurtle

2024-10-23 16:07 UTC, jonenst approved these changes

2024-10-23 16:36 UTC, sBouzols requested changes
I think you must remove the maven.yml file then

2024-10-23 16:36 UTC, sBouzols commented on src/main/resources/db/changelog/changesets/changelog_20240503T080101Z.xml
> +<?xml version="1.1" encoding="UTF-8" standalone="no"?>
remove those changelog files

2024-10-24 13:18 UTC, sBouzols approved these changes

2024-10-24 14:31 UTC, merged