Finish migration to gridexplore
gridsuite/directory-server pull request #39
Opened 2021-10-26 08:41 UTC by FranckLecuyer

2021-11-10 13:21 UTC, laurgarn approved these changes

2021-11-10 13:21 UTC, laurgarn commented on src/main/java/org/gridsuite/directory/server/DirectoryService.java
> +                return Mono.empty().then();
'then()' not required. As it return an empty mono, as Mono.empty() does.

2021-11-15 09:16 UTC, niconoir requested changes

2021-11-15 16:01 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/directory/server/DirectoryController.java
> +    @GetMapping(value = "/directories/{directoryUuid}/{elementName}/exists")
Done

2021-11-16 13:28 UTC, niconoir approved these changes

2021-11-17 14:43 UTC, merged