check if element exists before creation
gridsuite/directory-server pull request #47
Opened 2021-12-14 07:40 UTC by AbdelHedhili

Signed-off-by: Abdelsalem <abdelsalem.hedhili@rte-france.com>

2021-12-14 11:32 UTC, sBouzols requested changes

2021-12-14 11:32 UTC, sBouzols commented on src/main/java/org/gridsuite/directory/server/DirectoryService.java
> +            return insertElement(elementAttributes, parentDirectoryUuid).doOnSuccess(unused2 -> emitDirectoryChanged(
unused2 ? why 2 ?

2021-12-14 11:32 UTC, sBouzols commented on src/main/java/org/gridsuite/directory/server/DirectoryService.java
> +        return (long) directoryElementRepository.findByNameAndParentIdAndType(elementName, parentDirectoryUuid, type).size() > 0;
you change parameters order here, no big deal

2021-12-14 11:32 UTC, sBouzols commented on src/main/java/org/gridsuite/directory/server/DirectoryController.java
> +    @Operation(summary = "Check if the element exists in the given directory")
`Check if an element with this name and this type already exists in the given directory `?

2021-12-14 11:32 UTC, sBouzols commented on src/main/java/org/gridsuite/directory/server/DirectoryController.java
> +        return ResponseEntity.ok().body(service.elementExistsMono(directoryUuid, elementName, type));
HEAD request method shouldn't return a body ! It was like that before but it's not good.
cf. warning : https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD

2021-12-14 14:17 UTC, etiennehomer commented on src/main/java/org/gridsuite/directory/server/DirectoryService.java
> +        return (long) directoryElementRepository.findByNameAndParentIdAndType(elementName, parentDirectoryUuid, type).size() > 0;
Why this cast to (long) ?

2021-12-15 10:52 UTC, sBouzols approved these changes

2021-12-15 11:24 UTC, etiennehomer approved these changes

2021-12-15 11:24 UTC, etiennehomer commented on src/main/java/org/gridsuite/directory/server/DirectoryService.java
> +            return Mono.error(new DirectoryException(NOT_ALLOWED));
Add constant ALREADY_EXISTS ?

2021-12-15 15:18 UTC, merged