Get all element parents
gridsuite/directory-server pull request #56
Opened 2022-03-29 12:50 UTC by archendel

2022-04-01 09:21 UTC, sBouzols requested changes

2022-04-01 09:31 UTC, archendel commented on src/main/java/org/gridsuite/directory/server/DirectoryService.java
> +            .filter(e -> STUDY.equals(e.getType()) || e.isAllowed(userId))
fixed + new test to cover the case

2022-04-01 09:31 UTC, archendel commented on src/main/java/org/gridsuite/directory/server/DirectoryController.java
> +    public ResponseEntity<Flux<ElementAttributes>> getElementParent(@PathVariable("elementUuid") UUID elementUuid,
changed

2022-04-04 08:17 UTC, sBouzols approved these changes

2022-04-05 08:36 UTC, jonenst approved these changes

2022-04-05 08:37 UTC, merged