centralize notifications in directory service
gridsuite/directory-server pull request #71
Opened 2022-09-13 07:38 UTC by YenguiSeddik

2022-09-21 09:36 UTC, SlimaneAmar requested changes

2022-09-21 09:36 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/directory/server/NotificationService.java
> +
Add  message `PostCompletion` ?

2022-09-21 09:36 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/directory/server/DirectoryService.java
> +        notificationService.emitDirectoryChanged(directoryUuid, elementName, userId, null, isPrivate, isRoot, notificationType);
Remove this method

2022-09-21 10:36 UTC, YenguiSeddik commented on src/main/java/org/gridsuite/directory/server/NotificationService.java
> +
ok. done.

2022-09-21 10:36 UTC, YenguiSeddik commented on src/main/java/org/gridsuite/directory/server/DirectoryService.java
> +        notificationService.emitDirectoryChanged(directoryUuid, elementName, userId, null, isPrivate, isRoot, notificationType);
ok. done

2022-09-21 14:06 UTC, bendaamerahm approved these changes

2022-09-26 07:13 UTC, SlimaneAmar approved these changes

2022-09-26 13:25 UTC, merged